context:
  version: "2.2.0"

package:
  name: blitz
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/blitz/-/blitz-${{ version }}.tgz
  sha256: 5492519600fb73c97d119b46b73bd89790a3a39b6258d05726265119753b95e4

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - blitz --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Missing Fullstack Toolkit for Next.js
  homepage: https://blitzjs.com/
  repository: https://github.com/blitz-js/blitz

extra:
  recipe-maintainers:
    - danielnachun
